### ISSUE TITLE
I18n for the active record part

### ISSUE THREAD

**Issue by Preen** [kreativgebiet/rich#199]
Hi
I can't seem to get how to translate the actual model and its attributes?
```yaml
sv:
  activerecord:
    models:
      rich_file:
        one: Dokument
        other: Dokument
```
